CREATE SCHEMA IF NOT EXISTS DEMO;

DROP TABLE IF EXISTS DEMO.USERS;

CREATE TABLE DEMO.USERS (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  username VARCHAR(250) NOT NULL,
  password VARCHAR(250) NOT NULL,
  info VARCHAR(250) NOT NULL,
  deleted BOOLEAN DEFAULT FALSE
);